In [1]:
from settings import CSV_CITIES, CSV_SCHOOLS
from apps.cities.cities import show_graph, prepare_data_from_csv
from apps.cities.merge import merge_cities_and_schools


if __name__ == '__main__':
    cities = prepare_data_from_csv(CSV_CITIES)
    merged = merge_cities_and_schools(CSV_CITIES, CSV_SCHOOLS)
    print(merged)
    # show_graph(cities, 10)

               ville_nom  ville_population_2012 ville_code_commune  \
32  BOULOGNE-BILLANCOURT                 112200              92012
49            VERSAILLES                  86700              78646
0                  PARIS                2211000              75056
6             STRASBOURG                 272100              67482
10                RENNES                 206700              35238
25      CLERMONT-FERRAND                 139000              63113
40             MONTREUIL                 102200              93048
26                 TOURS                 135500              37261
3               TOULOUSE                 439600              31555
35                 ROUEN                 109400              76540
4                   NICE                 344900              06088
20       AIX-EN-PROVENCE                 142700              13001
2                   LYON                 474900              69123
29              BESANCON                 117600              25056
9                  LILLE                 225800              59350
15              GRENOBLE                 156700              38185
18           SAINT-DENIS                 145022              97411
16                 DIJON                 151600              21231
30             PERPIGNAN                 116700              66136
17                ANGERS                 148400              49007
31               ORLEANS                 113300              45234
42             DUNKERQUE                  93600              59183
5                 NANTES                 283300              44109
34                  CAEN                 109900              14118
43             TOURCOING                  92600              59599
21                 BREST                 142100              29019
33              MULHOUSE                 111900              68224
27                AMIENS                 134400              80021
38            SAINT-PAUL                 103346              97415
46              POITIERS                  89300              86194
14                TOULON                 166700              83137
1              MARSEILLE                 851400              13055
24               LIMOGES                 140100              87085
44               AVIGNON                  90100              84007
8               BORDEAUX                 235900              33063
28                  METZ                 122800              57463
7            MONTPELLIER                 253000              34172
36                 NANCY                 106400              54395
19               LE MANS                 143500              72181
23                 NIMES                 140300              30189
11                 REIMS                 181500              51454
22          VILLEURBANNE                 141100              69266
13         SAINT-ETIENNE                 172700              42218
37           SAINT-DENIS                 103700              93066
41               ROUBAIX                  95900              59512
12              LE HAVRE                 178800              76351
48        FORT-DE-FRANCE                  87216              97209
47               CRETEIL                  89300              94028
45              NANTERRE                  89600              92050
39            ARGENTEUIL                 103300              95018

    Taux Brut de Réussite Total séries  Taux_Mention_brut_toutes_series  \
32                           95.681818                        72.000000
49                           97.612245                        73.428571
0                            93.943806                        65.958904
6                            92.537190                        59.647059
10                           93.912621                        60.321429
25                           93.936508                        60.166667
40                           91.771429                        58.400000
26                           93.814286                        59.450000
3                            93.045113                        58.131579
35                           92.820896                        57.833333
4                            93.270833                        58.071429
20                           93.422535                        57.380952
2                            93.261044                        56.680556
29                           93.705882                        56.857143
9                            91.675926                        55.586207
15                           92.915663                        56.250000
18                           91.457143                        55.300000
16                           92.962500                        56.045455
30                           91.538462                        55.000000
17                           94.935065                        56.681818
31                           91.267857                        54.250000
42                           94.047619                        55.583333
5                            92.978571                        54.850000
34                           92.738095                        54.500000
43                           90.452381                        52.700000
21                           94.690476                        55.000000
33                           88.777778                        51.416667
27                           89.068966                        51.280000
38                           92.937500                        53.100000
46                           92.241379                        52.411765
14                           92.352941                        52.062500
1                            90.553333                        50.882353
24                           91.693548                        51.388889
44                           91.775510                        51.214286
8                            90.664286                        50.050000
28                           91.014493                        49.736842
7                            89.304348                        48.750000
36                           91.043478                        49.400000
19                           92.040816                        48.642857
23                           89.875000                        46.812500
11                           89.213483                        46.384615
22                           88.137931                        45.500000
13                           90.932432                        45.450000
37                           84.608696                        40.571429
41                           84.163265                        38.928571
12                           85.781818                        38.333333
48                           88.428571                        39.142857
47                           87.377778                        38.428571
45                           80.285714                        30.000000
39                           80.535714                        28.125000

    Note globale
32     75.249406
49     75.224754
0      70.211020
6      64.457391
10     64.231440
25     64.050355
40     63.636364
26     63.369880
3      62.476768
35     62.306373
4      62.261080
20     61.420890
2      60.776239
29     60.676173
9      60.633374
15     60.538771
18     60.465480
16     60.288239
30     60.084034
17     59.705882
31     59.440423
42     59.101266
5      58.992087
34     58.767651
43     58.262701
21     58.083983
33     57.916145
27     57.573364
38     57.135171
46     56.820231
14     56.373408
1      56.190480
24     56.044171
44     55.803869
8      55.203656
28     54.647167
7      54.588608
36     54.259790
19     52.849224
23     52.086231
11     51.992831
22     51.623631
13     49.982167
37     47.951843
41     46.253637
12     44.687014
48     44.264943
47     43.979799
45     37.366548
39     34.922395